[versions]
agp = "8.13.1"
kotlin = "2.2.21"
coreKtx = "1.17.0"
junit = "4.14-SNAPSHOT"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.12.0"
composeBom = "2025.11.01"

# Jetpack
lifecycleViewmodel = "2.10.0"
lifecycleViewmodelCompose = "2.10.0"
navigation = "2.9.6"
navigationCompose = "2.9.6"
room = "2.8.4"
datastore = "1.2.0"
workManager = "2.11.0"
startup = "1.2.0"
paging = "3.3.5"
material3 = "1.4.0"

# Hilt
hilt = "2.57.2"
hiltNavigationCompose = "1.3.0"

# Gson
gson = "2.13.2"

# Network
retrofit = "3.0.0"
okhttp = "5.3.1"

# Image
coil = "2.7.0"
pictureSelector = "v3.11.2"

# Chart
mpandroidchart = "3.1.0"

# ExoPlayer
exoplayer = "2.19.1"

# UI
dsltablayout = "3.0.0"
baseRecyclerViewAdapterHelper = "4.3.2"
autosize = "1.2.1"

# Permission
xxpermissions = "26.5"
# Toaster
toaster = "13.8"

# Utils
utilcodex = "1.31.1"

# Chucker
chucker = "4.2.0"

[libraries]
# AndroidX Core
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodel" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" }

# Compose
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref ="material3" }
androidx-compose-material = { group = "androidx.compose.material", name = "material" }
androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
androidx-compose-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }

# Navigation
androidx-navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation" }
androidx-navigation-ui = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation" }

# Room
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }

# DataStore
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }

# WorkManager
androidx-work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workManager" }

# Startup
androidx-startup-runtime = { group = "androidx.startup", name = "startup-runtime", version.ref = "startup" }

# Paging
androidx-paging-runtime = { group = "androidx.paging", name = "paging-runtime-ktx", version.ref = "paging" }
androidx-paging-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "paging" }

# Hilt
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationCompose" }

# Network
retrofit-core = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
okhttp-core = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okhttp-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
gson-core = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

# Image
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
# PictureSelector 基础 (必须)
picture-selector = { group = "io.github.lucksiege", name = "pictureselector", version.ref = "pictureSelector" }
# PictureSelector 图片压缩 (按需引入)
picture-selector-compress = { group = "io.github.lucksiege", name = "compress", version.ref = "pictureSelector" }
# PictureSelector 图片裁剪 (按需引入)
picture-selector-ucrop = { group = "io.github.lucksiege", name = "ucrop", version.ref = "pictureSelector" }
# PictureSelector 自定义相机 (按需引入)
picture-selector-camerax = { group = "io.github.lucksiege", name = "camerax", version.ref = "pictureSelector" }

# Media
exoplayer-core = { group = "com.google.android.exoplayer", name = "exoplayer-core", version.ref = "exoplayer" }
exoplayer-ui = { group = "com.google.android.exoplayer", name = "exoplayer-ui", version.ref = "exoplayer" }

# Chart
mpandroidchart-core = { group = "com.github.PhilJay", name = "MPAndroidChart", version.ref = "mpandroidchart" }

# UI
dsltablayout-core = { group = "com.github.angcyo", name = "DslTabLayout", version.ref = "dsltablayout" }
base-recyclerview-adapter-helper = { group = "io.github.cymchad", name = "BaseRecyclerViewAdapterHelper4", version.ref = "baseRecyclerViewAdapterHelper" }
autosize-core = { group = "me.jessyan", name = "autosize", version.ref = "autosize" }

# Permission
xxpermissions-core = { group = "com.github.getActivity", name = "XXPermissions", version.ref = "xxpermissions" }
# Toaster
toaster = { group = "com.github.getActivity", name = "Toaster", version.ref = "toaster"}

# Utils
utilcodex = { group = "com.blankj", name = "utilcodex", version.ref = "utilcodex"}

# Chucker
chucker-debug = { group = "com.github.chuckerteam.chucker", name = "library", version.ref = "chucker" }
chucker-release = { group = "com.github.chuckerteam.chucker", name = "library-no-op", version.ref = "chucker" }

# Test
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }

